import { useState } from 'react'
import { Button, Checkbox, FlexBox, Modal, ModalContainer, ModalContent, ModalContentItem, ModalHeading, Option, Select, TextField, Typography, useToast } from '@wanteddev/wds'
import { IconPencil, IconTrash } from '@wanteddev/wds-icon'
import ConfirmModal from '../../components/common/ConfirmModal'
import PageHeader from '../../components/common/PageHeader'
import DataTable, { type DataTableColumn } from '../../components/common/DataTable'
import FormItem from '../../components/common/FormItem'
import SearchField from '../../components/common/SearchField'
import StatusBadge, { type BadgeTone } from '../../components/common/StatusBadge'
import { useStudentCouncil } from '../studentCouncil/store'
import { type Admin, type AdminRole, type StudentCouncilDepartment, useAdminManagement } from './store'

const roleTone: Record<AdminRole, BadgeTone> = { 학생: 'neutral', 관리자: 'info' }
const departments: StudentCouncilDepartment[] = ['총무부', '집행부', '기획부', '복지부', '홍보부', '미디어부', '소통부']

export default function AdminManagementPage() {
  const toast = useToast(); const { admins, setAdmins } = useAdminManagement(); const { members } = useStudentCouncil()
  const [search, setSearch] = useState(''); const [memberSearch, setMemberSearch] = useState(''); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Admin | null>(null); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [bulkOpen, setBulkOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false); const [bulkRole, setBulkRole] = useState<AdminRole>('학생')
  const [draft, setDraft] = useState<Omit<Admin, 'id'>>({ name: '', studentId: '', role: '학생' })
  const filtered = admins.filter((a) => !search.trim() || a.name.includes(search.trim()) || a.studentId.includes(search.trim()))
  const candidates = members.filter((m) => m.name.includes(memberSearch.trim()) || m.studentId.includes(memberSearch.trim()))
  const showAdd = () => { setEditing(null); setDraft({ name: '', studentId: '', role: '학생' }); setMemberSearch(''); setOpen(true) }
  const save = () => { if (!draft.name || !draft.studentId) return; editing ? setAdmins((p) => p.map((a) => a.id === editing.id ? { ...draft, id: a.id } : a)) : setAdmins((p) => [...p, { ...draft, id: `admin_${Date.now()}` }]); toast({ content: editing ? '관리자 정보를 수정했어요.' : '관리자를 추가했어요.', variant: 'positive' }); setOpen(false) }
  const columns: DataTableColumn<Admin>[] = [
    { key: 'select', header: <Checkbox checked={filtered.length > 0 && filtered.every((r) => selectedIds.includes(r.id))} onCheckedChange={(checked) => setSelectedIds(checked ? filtered.map((r) => r.id) : [])} />, width: 48, align: 'center', render: (r) => <Checkbox checked={selectedIds.includes(r.id)} onCheckedChange={(checked) => setSelectedIds((prev) => checked ? [...prev, r.id] : prev.filter((id) => id !== r.id))} /> },
    { key: 'name', header: '이름', render: (r) => r.name }, { key: 'studentId', header: '학번', width: 160, render: (r) => r.studentId }, { key: 'role', header: '권한', width: 120, render: (r) => <StatusBadge label={r.role} tone={roleTone[r.role]} /> }, { key: 'department', header: '학생회 부서', width: 150, render: (r) => r.councilDepartment ?? '-' },
    { key: 'edit', header: '', width: 64, align: 'right', render: (r) => <Button variant="outlined" color="assistive" size="small" onClick={() => { setEditing(r); setDraft({ name: r.name, studentId: r.studentId, role: r.role, councilDepartment: r.councilDepartment }); setOpen(true) }}><IconPencil width={15} height={15} />수정</Button> },
  ]
  return <><PageHeader title="관리자 관리" description="Stream 접근 권한과 학생회 부서를 관리해요." /><FlexBox justifyContent="flex-end" style={{ gap: 12, marginBottom: 16 }}><SearchField value={search} onChange={setSearch} placeholder="이름 또는 학번 검색" /><Button variant="solid" color="primary" onClick={showAdd}>+ 관리자 추가하기</Button></FlexBox><FlexBox style={{ position: 'relative' }}>{selectedIds.length > 0 && <FlexBox alignItems="center" style={{ position: 'absolute', zIndex: 2, bottom: 'calc(100% + 12px)', height: 48, border: '1px solid var(--semantic-line-normal-normal)', borderRadius: 12, background: 'var(--semantic-background-elevated-normal)', overflow: 'hidden', boxShadow: '0 8px 20px rgba(0,0,0,.12)' }}><Typography variant="body2" weight="bold" style={{ padding: '0 16px', color: 'var(--semantic-primary-normal)' }}>{selectedIds.length}개 선택됨</Typography><button type="button" onClick={() => setBulkOpen(true)} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, height: '100%', padding: '0 16px', border: 0, borderLeft: '1px solid var(--semantic-line-normal-normal)', background: 'transparent', color: 'var(--semantic-label-normal)', font: 'inherit', fontWeight: 600, cursor: 'pointer' }}><IconPencil width={16} height={16} />권한 수정</button><button type="button" aria-label="선택한 관리자 삭제" onClick={() => setDeleteOpen(true)} style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 48, height: '100%', padding: 0, border: 0, borderLeft: '1px solid var(--semantic-line-normal-normal)', background: 'transparent', color: 'var(--semantic-status-negative)', cursor: 'pointer' }}><IconTrash width={16} height={16} /></button></FlexBox>}<DataTable columns={columns} rows={filtered} rowKey={(r) => r.id} emptyMessage="등록된 관리자가 없어요." style={{ width: '100%' }} /></FlexBox>
    <Modal open={open} onOpenChange={setOpen}><ModalContainer size="small"><ModalContent><ModalContentItem><ModalHeading>{editing ? '관리자 정보 수정' : '관리자 추가'}</ModalHeading></ModalContentItem><ModalContentItem style={{ gap: 20 }}>
      {!editing && <FormItem label="기존 회원 검색"><TextField value={memberSearch} placeholder="이름 또는 학번을 검색하세요" onChange={(e) => setMemberSearch(e.target.value)} />{memberSearch.trim() && <FlexBox flexDirection="column" style={{ marginTop: 8, border: '1px solid var(--semantic-line-normal-normal)', borderRadius: 8, overflow: 'hidden' }}>{candidates.map((m) => <button key={m.id} type="button" onClick={() => { setDraft({ ...draft, name: m.name, studentId: m.studentId }); setMemberSearch(m.name) }} style={{ padding: '10px 12px', border: 0, textAlign: 'left', background: 'transparent', cursor: 'pointer' }}>{m.name} · {m.studentId} · {m.department}</button>)}{candidates.length === 0 && <Typography variant="body2" style={{ padding: 12 }}>검색 결과가 없어요.</Typography>}</FlexBox>}</FormItem>}
      <FormItem label="이름"><TextField value={draft.name} disabled={!editing} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></FormItem><FormItem label="학번"><TextField value={draft.studentId} disabled={!editing} onChange={(e) => setDraft({ ...draft, studentId: e.target.value })} /></FormItem><FormItem label="권한"><Select value={draft.role} onChange={(v) => setDraft({ ...draft, role: v as AdminRole })}><Option value="학생">학생</Option><Option value="관리자">관리자</Option></Select></FormItem><FormItem label="학생회 부서"><Select value={draft.councilDepartment ?? ''} onChange={(v) => setDraft({ ...draft, councilDepartment: v ? v as StudentCouncilDepartment : undefined })}><Option value="">소속 없음</Option>{departments.map((d) => <Option key={d} value={d}>{d}</Option>)}</Select></FormItem>
    </ModalContentItem><ModalContentItem style={{ flexDirection: 'row', justifyContent: 'flex-end', gap: 8 }}><Button variant="outlined" color="assistive" onClick={() => setOpen(false)}>취소</Button><Button variant="solid" color="primary" onClick={save}>저장</Button></ModalContentItem></ModalContent></ModalContainer></Modal>
    <Modal open={bulkOpen} onOpenChange={setBulkOpen}><ModalContainer size="small"><ModalContent><ModalContentItem><ModalHeading>권한 일괄 수정</ModalHeading></ModalContentItem><ModalContentItem><FormItem label="변경할 권한"><Select value={bulkRole} onChange={(value) => setBulkRole(value as AdminRole)}><Option value="학생">학생</Option><Option value="관리자">관리자</Option></Select></FormItem></ModalContentItem><ModalContentItem style={{ flexDirection: 'row', justifyContent: 'flex-end', gap: 8 }}><Button variant="outlined" color="assistive" onClick={() => setBulkOpen(false)}>취소</Button><Button variant="solid" color="primary" onClick={() => { setAdmins((prev) => prev.map((admin) => selectedIds.includes(admin.id) ? { ...admin, role: bulkRole } : admin)); setBulkOpen(false); toast({ content: '선택한 관리자의 권한을 수정했어요.', variant: 'positive' }) }}>수정</Button></ModalContentItem></ModalContent></ModalContainer></Modal><ConfirmModal open={deleteOpen} onOpenChange={setDeleteOpen} title="선택한 관리자를 삭제할까요?" description={`선택한 ${selectedIds.length}명의 관리자 권한이 삭제돼요.`} confirmLabel="삭제" tone="negative" onConfirm={() => { setAdmins((prev) => prev.filter((admin) => !selectedIds.includes(admin.id))); setSelectedIds([]); toast({ content: '선택한 관리자를 삭제했어요.', variant: 'positive' }) }} /></>
}
